### ISSUE TITLE
Prometheus metrics for blacklist words and etc

### ISSUE THREAD

**Issue by emyfops** [Elliesaur/Tox#10]
So, I continued the project on my side
And I was wondering if you would accept my idea to add metrics for monitoring

I am already doing the code, but this could be useful for big server like mine (1000 members)
![image](https://user-images.githubusercontent.com/46357922/147615571-ebec74df-d996-4e5c-a642-d32a1863a05f.png)

These metrics can be used with grafana for full monitoring etc

**Comment by Elliesaur** [comment]
The project was never intended for production use but you're more than welcome to suggest changes. I'd recommend running your own instance of the bot and first of all updating Discord.js to v13 which changes a lot of things.
