### ISSUE TITLE
Nothing work, need fix

### ISSUE THREAD

**Issue by emyfops** [Elliesaur/Tox#7]
(node:30) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'logChannelId' of undefined
    at Bot.<anonymous> (/usr/src/app3/src/Bot.js:147:33)
    at Generator.next (<anonymous>)
    at /usr/src/app3/src/Bot.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app3/src/Bot.js:4:12)
    at /usr/src/app3/src/Bot.js:145:96
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    
    To every messages sent
    Node v14

**Comment by Elliesaur** [comment]
This is because discord.js is still v12. It needs to be updated to v13 to support node v14.

**Comment by emyfops** [comment]
> This is because discord.js is still v12. It needs to be updated to v13 to support node v14.

Sorry for disturbing
If the MongoDB connection is invalid, no command will work

- [ ] Add debug information if MongoDB is invalid, example: "Make sure to have a valid mongodb configuration or no command will work"
