### ISSUE TITLE
Regexes not detecting

### ISSUE THREAD

**Issue by emyfops** [Elliesaur/Tox#8]

**Comment by Elliesaur** [comment]
Hiya,

Flags are already specified. You do not specify them in the current implementation. See https://github.com/Elliesaur/Detox/blob/master/src/Bot.ts#L135 for flag default (gi).

Have you added a blacklist channel list?

**Comment by Edouard127** [comment]
Yes I do, it works with certain
But doesn't with others

**Comment by Elliesaur** [comment]
Review your blacklist channel list. Try running the bot locally.

**Comment by Edouard127** [comment]
> Review your blacklist channel list. Try running the bot locally.

I did some testing
And I found out if a single regex is invalid, it will stop comparing at this regex


Example:
1. Good regex
2. Good regex
3. Bad Regex
4. Good regex (enter swear here)

Member send "(enter swear here)"
It will stop at the third line and will not delete the message

**Comment by Elliesaur** [comment]
Yeah. I see why. Try is around whole for loop. https://github.com/Elliesaur/Detox/blob/master/src/Bot.ts#L133
Submit a pull request with the change to make it around each iteration, otherwise I'll get to it another time. Holidays and such.

**Comment by Edouard127** [comment]
#9
